spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCcompliantTimezoneShift=true&useLeagacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

    #Pour l'api Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Specify DBMS
  jpa:
    database: mysql
    show-sql: false
    properties:


    # Hibernate DDL Auto (create, create-drop, update)
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        ejb:
          interceptor: com.akb.gestionstock.interceptor.Interceptor
#Server Port
server:
  port: 8081

#Flikr Api for saving project images
flickr:
  apiKey: 07701c1b5559fa5b823b3e2f701313a0
  apiSecret: 5a0ebc63bb651d2d
  appKey: 72157720874057053-eaa2db77dd7d8275
  appSecret: 70ec6f90402d8735
